#!/bin/bash


# user params
INRES="1280x800"            # input resolution
OUTRES="768x480"            # output resolution
FPS="15"                    # target FPS
GOP="30"                    # i-frame interval, should be double of FPS,
GOPMIN="15"                 # min i-frame interval, should be equal to fps,
THREADS="2"                 # max 6
CBR="800k"                  # constant bitrate (should be between 1000k - 3000k)
QUALITY="veryfast"          # one of the many FFMPEG preset
AUDIO_RATE="44100"          # audio bitrate (44100 is fine)
STREAM_KEY=""               # your streaming key goes here
HIDE_LOGS="-loglevel quiet" # to hide logs
HIDE_LOGS=""


# ffmpeg params
SCREENCAP_INPUT="-f x11grab -s "$INRES" -r "$FPS" -i :0.0"
# WEBCAM_INPUT="-f v4l2 -i /dev/video0"
WEBCAM_INPUT="-f v4l2 -video_size 160x120 -framerate 30 -i /dev/video0"
# 640x480 352x288 320x240 176x144 160x120
STATIC_INPUT="-i me.png"
MAIN_INPUT=$SCREENCAP_INPUT
# MAIN_INPUT=$STATIC_INPUT
# MAIN_INPUT=$WEBCAM_INPUT
# OVERLAY_INPUT=$SCREENCAP_INPUT
# OVERLAY_INPUT=$STATIC_INPUT
OVERLAY_INPUT=$WEBCAM_INPUT
# OVERLAY_INPUT=
# from man ffmpeg-filters:
#   Insert a transparent PNG logo in the bottom left corner of the input,
#       using the ffmpeg tool with the "-filter_complex" option:
#       $ ffmpeg -i input -i logo -filter_complex 'overlay=10:main_h-overlay_h-10' output
# OVERLAY_FILTER="-filter_complex \"overlay=W-w-8:y=8:format=yuv444\""
# OVERLAY_FILTER="-filter_complex \"overlay=W-w-8:y=8:format=rgb\""
OVERLAY_FILTER=-filter_complex 'overlay=10:main_h-overlay_h-10'
# OVERLAY_FILTER="-lavfi \"overlay=W-w-8:y=8:format=rgb\""
# OVERLAY_FILTER="-vf \"movie=me.png [watermark]; [in][watermark] overlay=10:10 [out]\""
# OVERLAY_FILTER=-vf "drawtext=text=this is a \\\\\\'string\\\\\\'\\\\: may contain one\\, or more\\, special characters"
# OVERLAY_FILTER=-vf "drawbox=x=10:y=10:w=100:h=100:color=pink@0.5:t=max"
# OVERLAY_FILTER=-vf "drawtext=text=this is some text"
# OVERLAY_FILTER=-vf "color=color=red@.3:size=WxH [over]; [in][over] overlay [out]"
# OVERLAY_FILTER=
# AUDIO_INPUT="-f alsa -i hw:0"
AUDIO_INPUT="-f jack -i ffmpeg"
STREAM_OUTPUT="-f flv -ac 2 -ar $AUDIO_RATE -vcodec libx264 -keyint_min 3 \
               -b:v $CBR -minrate $CBR -maxrate $CBR -pix_fmt yuv420p     \
               -s $OUTRES -preset $QUALITY -acodec mp3 -bufsize $CBR"
THREADS="-threads $THREADS $HIDE_LOGS"
RTMP_URL="rtmp://usmedia3.livecoding.tv:1935/livecodingtv/$LIVECODING_STREAM_KEY"
# RTMP_URL=test.mp4


echo "\$ ffmpeg $MAIN_INPUT $OVERLAY_INPUT $OVERLAY_FILTER $AUDIO_INPUT $STREAM_OUTPUT $THREADS $RTMP_URL"

#        $OVERLAY_FILTER \ # TODO: nfg
ffmpeg $MAIN_INPUT     \
       $OVERLAY_INPUT  \
       -filter_complex 'overlay=main_w-overlay_w:main_h-overlay_h' \
       $AUDIO_INPUT    \
       $STREAM_OUTPUT  \
       $THREADS        \
       $RTMP_URL
