#!/bin/bash


# user params
INRES="1280x800"            # input resolution
OUTRES="768x480"            # output resolution
FPS="15"                    # target FPS
GOP="30"                    # i-frame interval, should be double of FPS,
GOPMIN="15"                 # min i-frame interval, should be equal to fps,
THREADS="2"                 # max 6
CBR="800k"                  # constant bitrate (should be between 1000k - 3000k)
QUALITY="veryfast"          # one of the many FFMPEG preset
AUDIO_RATE="44100"          # audio bitrate (44100 is fine)
STREAM_KEY=""               # your streaming key goes here
HIDE_LOGS="-loglevel quiet" # to hide logs
HIDE_LOGS=""


# ffmpeg params
SCREENCAP_INPUT="-f x11grab -s "$INRES" -r "$FPS" -i :0.0"
WEBCAM_INPUT="-f v4l2 -i /dev/video0"
# from man ffmpeg-filters:
#   Insert a transparent PNG logo in the bottom left corner of the input,
#       using the ffmpeg tool with the "-filter_complex" option:
#       $ ffmpeg -i input -i logo -filter_complex 'overlay=10:main_h-overlay_h-10' output
# TEST_OVERLAY="-i me.png -filter_complex \"overlay=W-w-8:y=8:format=yuv444\""
# TEST_OVERLAY="-i me.png -filter_complex \"overlay=W-w-8:y=8:format=rgb\""
TEST_OVERLAY="-i 'me.png' -filter_complex 'overlay=10:main_h-overlay_h-10'"
# TEST_OVERLAY="-i me.png -lavfi \"overlay=W-w-8:y=8:format=rgb\""
# TEST_OVERLAY="-vf \"movie=me.png [watermark]; [in][watermark] overlay=10:10 [out]\""
# TEST_OVERLAY=-vf "drawtext=text=this is a \\\\\\'string\\\\\\'\\\\: may contain one\\, or more\\, special characters"
# TEST_OVERLAY=-vf "drawbox=x=10:y=10:w=100:h=100:color=pink@0.5:t=max"
# TEST_OVERLAY=-vf "drawtext=text=this is some text"
# TEST_OVERLAY=-vf "color=color=red@.3:size=WxH [over]; [in][over] overlay [out]"
# AUDIO_INPUT="-f alsa -i hw:0"
MAIN_INPUT=$SCREENCAP_INPUT
# OVERLAY_INPUT=$TEST_OVERLAY
OVERLAY_INPUT=
AUDIO_INPUT="-f jack -i ffmpeg"
STREAM_OUTPUT="-f flv -ac 2 -ar $AUDIO_RATE -vcodec libx264 -keyint_min 3 \
               -b:v $CBR -minrate $CBR -maxrate $CBR -pix_fmt yuv420p     \
               -s $OUTRES -preset $QUALITY -acodec mp3 -bufsize $CBR"
THREADS="-threads $THREADS $HIDE_LOGS"
RTMP_URL="rtmp://usmedia3.livecoding.tv:1935/livecodingtv/$LIVECODING_STREAM_KEY"
# RTMP_URL=test.mp4


# ffmpeg $MAIN_INPUT    \
#        $OVERLAY_INPUT \
ffmpeg -i 'me.png'                                      \
       -f x11grab -s "$INRES" -r "$FPS" -i :0.0         \
       -filter_complex 'overlay=10:main_h-overlay_h-10' \
       $AUDIO_INPUT   \
       $STREAM_OUTPUT \
       $THREADS       \
       $RTMP_URL
